### ISSUE TITLE
not enough memory

### ISSUE THREAD

**Issue by sl00k** [nuriel77/goshimmer-playbook#5]
TASK [common : stop if memory is too small] ***********************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "ansible_memtotal_mb >= min_required_memtotal_mb", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"

why do you check for it?

**Comment by nuriel77** [comment]
@sl00k because at least initially, there was no chance to run a goshimmer node with less than 1500MB RAM.
There's a pending PR to lower the requirement to 900MB... We'll see how much a node can survive after some optimisation is done to goshimmer.

**Comment by nuriel77** [comment]
Lowered to 900MB in this PR https://github.com/nuriel77/goshimmer-playbook/pull/6
